# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: job1
    steps:
    - script: echo Hello, $(name)!
      displayName: 'STAGE BUILD 1ST JOB'

- stage: Dev
  dependsOn: Build
  jobs:
  - job: job1
    steps:
    - script: echo Running task1
      displayName: 'STAGE DEV 1st JOB'
    - script: echo Running task2
      displayName: 'STAGE DEV 2nd JOB'

- stage: Test
  dependsOn: Build
  jobs:
    - job: job1
      steps:
      - script: echo Running task1
        displayName: 'STAGE TEST 1st JOB'
      - script: echo Running task2
        displayName: 'STAGE TEST 2nd JOB'
      - script: echo Running task3
        displayName: 'STAGE TEST 3rd JOB'

- stage: QA
  dependsOn: 
  - Build
  - Test
  jobs:
    - job: job1
      steps:
      - script: echo Running task1
        displayName: 'STAGE QA 1st JOB'
    - job: job2
      dependsOn: job1
      steps:
      - script: echo Running task1
        displayName: 'STAGE QA 2nd JOB'


