# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml

trigger:
- main

pool:
  vmImage: ubuntu-latest

stages:
- stage: Build
  jobs:
  - job: job1
    steps:
    - bash: echo $(Build.Repository.LocalPath)
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: ls $(System.DefaultWorkingDirectory)
    - bash: java --version
    - bash: npm --version
    - bash: echo $(Build.ArtifactStagingDirectory)
    - bash: pip freeze | xargs tee requirements.txt | xargs cat 
    - bash: find "requirements.txt" | xargs echo

# - stage: Dev
#   dependsOn: Build
#   jobs:
#   - job: job1
#     steps:
#     - script: echo Running task1
#       displayName: 'STAGE DEV 1st JOB'
#     - script: echo Running task2
#       displayName: 'STAGE DEV 2nd JOB'
